# This is a basic workflow to help you get started with Actions

name: deploy 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # just for test, remove it later

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    outputs:
      version: ${{ steps.detect_version.outputs.version }}      
    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.PORT }}
          script: '$HOME/reload'



          
